name = "QuantumESPRESSO"
uuid = "82ee9cd6-8aeb-11e9-04e5-bd3792d65b20"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
Crystals = "2c71e7ee-d617-5e33-8739-0c480ea2ee55"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
