name = "QuantumESPRESSO"
uuid = "95228164-aa68-11e9-35aa-d79ea5c4658d"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.2-DEV"

[deps]
QuantumESPRESSOParser = "a780ab42-b33a-11e9-16c1-a92d75b2a626"
QuantumESPRESSOBase = "51b62caa-b28f-11e9-38c2-1f67cb498e05"
QuantumESPRESSOCommands = "f713baf6-9299-4878-8719-8ad597e49a7b"
QuantumESPRESSOFormatter = "a4e7ca57-d8d8-4f74-9c0b-0b18081c205e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
QuantumESPRESSOParser = "0.1"
julia = "1.3"
QuantumESPRESSOBase = "0.1"
QuantumESPRESSOCommands = "0.2"
QuantumESPRESSOFormatter = "0.1"

[targets]
test = ["Test"]
