name = "QuantumESPRESSO"
uuid = "95228164-aa68-11e9-35aa-d79ea5c4658d"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.10.1"

[deps]
QuantumESPRESSOBase = "51b62caa-b28f-11e9-38c2-1f67cb498e05"
QuantumESPRESSOFormatter = "a4e7ca57-d8d8-4f74-9c0b-0b18081c205e"
QuantumESPRESSOParser = "a780ab42-b33a-11e9-16c1-a92d75b2a626"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
QuantumESPRESSOBase = "0.11"
QuantumESPRESSOFormatter = "0.3"
QuantumESPRESSOParser = "0.4"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
