name = "QuantumESPRESSO"
uuid = "95228164-aa68-11e9-35aa-d79ea5c4658d"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.2.0"

[deps]
QuantumESPRESSOBase = "51b62caa-b28f-11e9-38c2-1f67cb498e05"
QuantumESPRESSOParsers = "a780ab42-b33a-11e9-16c1-a92d75b2a626"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
